# Generated by Django 5.0.7 on 2024-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTemplateSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slider', models.CharField(db_comment='текст акции на слайдере', max_length=64)),
                ('body_slider', models.CharField(db_comment='описание акции на слайдере', max_length=128)),
                ('photo_slider', models.ImageField(help_text='фотография для слайдера в последнем блоке', upload_to='')),
            ],
            options={
                'verbose_name': 'контент',
                'verbose_name_plural': 'слайдеры',
                'db_table': 'index_slider',
            },
        ),
        migrations.CreateModel(
            name='TemplateContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_title', models.CharField(db_comment='секция коллекции, заголовок', max_length=32)),
                ('important_title', models.CharField(db_comment='секция важности бренда, заголовок', max_length=32)),
                ('life_title', models.CharField(db_comment='секция достижений, заголовок', max_length=32)),
                ('small_title', models.CharField(db_comment='секция достижений, боковой заголовок', max_length=24)),
                ('small_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_comment='Название категории', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(db_comment='слаг(название категории на английском)', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_comment='описание изделия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, db_comment='новая цена(при уценке или дорожании)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_comment='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(db_comment='слаг (название изделия на английском)', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_comment='название изделия', max_length=128),
        ),
    ]
