# Generated by Django 5.0.7 on 2024-08-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_templatecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextemplateslide',
            name='body_slider',
            field=models.CharField(help_text='описание акции на слайдере', max_length=128),
        ),
        migrations.AlterField(
            model_name='indextemplateslide',
            name='title_slider',
            field=models.CharField(help_text='текст акции на слайдере', max_length=64),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='collection_title',
            field=models.CharField(help_text='секция коллекции, заголовок', max_length=32),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='important_title',
            field=models.CharField(help_text='секция важности бренда, заголовок', max_length=32),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='life_title',
            field=models.CharField(help_text='секция достижений, заголовок', max_length=32),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='small_description',
            field=models.TextField(help_text='секция достижений, боковой текст'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='small_title',
            field=models.CharField(help_text='секция достижений, боковой заголовок', max_length=24),
        ),
    ]
