# Generated by Django 5.0.7 on 2024-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_indextemplateslide_body_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextemplateslide',
            name='body_slider',
            field=models.CharField(help_text='описание акции на слайдере', max_length=160),
        ),
    ]
