# Generated by Django 5.0.7 on 2024-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_indextemplateslide_photo_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
