# Generated by Django 5.0.7 on 2024-08-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, db_comment='новая цена(при уценке или дорожании)', null=True),
        ),
    ]
